## 난수 생성 함수
- random

In [ ]:
import numpy as np

In [ ]:
a = np.random.rand(2, 2)  # 0 ~ 1 사이에 값 랜덤
print(a)

[[0.43300954 0.93504227]
 [0.94404352 0.19834139]]


In [ ]:
b = np.random.randn(2, 2)  # 평균이 0, 분산이 1 : 표준 정규 분포
print(b)

[[-1.76175158 -1.33461939]
 [ 0.68765725 -0.48672757]]


In [ ]:
c = np.random.randint(0, 10, size=5)  # 랜덤 정수 size는 개수 0 ~ 10까지 
print(c)

[5 6 2 8 3]


In [ ]:
c2 = np.random.randint(0, 10, size=(2, 2))  # 행렬 형태도 가능
print(c2)

[[3 6]
 [7 9]]


In [ ]:
d = np.arange(10)  # 0 ~ 9까지 값을 생성
np.random.shuffle(d)  # 무작위로 섞어줌, 복사본 생성이 x, 원본 값이 변한다.
print(d)

[5 8 9 4 3 7 0 2 1 6]


In [ ]:
choice = np.random.choice(d, 5)  # d 안에서 5개를 뽑아줘, 중복 허용
choice = np.random.choice(d, 5, replace=False)  # 중복 허용 x
choice = np.random.choice(d, 5, p=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])  # p 확률에 따라 뽑는다. 범위 : 0 ~ 1. 전체 확률 1로 맞춰줘야 함.
print(choice)

[7 0 9 3 4]


In [ ]:
# permutation 순열
a = np.arange(10)
a_p = np.random.permutation(a)
print(a_p)

[2 7 8 3 6 4 5 1 9 0]


In [ ]:
# 정규분포를 따르는 난수 생성
# a = np.random.normal('평균', '표준편차', '갯수')
a = np.random.normal(0, 1, 3)  # 표준 정규 분포 : 평균 0, 분산 1
print(a)

[-0.8547317  -2.07468111  0.00386023]


# Pandas
- 데이터 자체를 분석, 파악
- 표
- 데이터 다루는 데 초점
- 정렬, 필터링, 그룹화, 집계

- 데이터 로딩 및 저장
- 데이터 인덱싱 및 슬라이싱
- 결측치 처리
- 데이터 변환
- 데이터 집계 및 그룹화
---
- 시계열 데이터 처리
- 데이터 시각화

## 1. Series(시리즈)
- 인덱스를 지정할 수 있음

In [ ]:
import pandas as pd

In [ ]:
# 리스트
s = pd.Series([1, 2, 3, 4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
# 딕셔너리
s2 = pd.Series({'a':1, 'b':2, 'c':3, 'd':4})
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [ ]:
# 스칼라
s3 = pd.Series(5, index=[0, 1, 2])
print(s3)

0    5
1    5
2    5
dtype: int64


In [ ]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


## 슬라이싱

In [ ]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
series[0:4]

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
series[:-1]

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


### Boolean Indexing




In [ ]:
series > 2

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [ ]:
series[series > 2]   #  a[a조건]

2    3
3    4
4    5
dtype: int64

In [ ]:
# 5보다 작은 시리즈 만들기

series[series < 5]

0    1
1    2
2    3
3    4
dtype: int64

## Seires 산술연산

In [ ]:
series + 100

0    101
1    102
2    103
3    104
4    105
dtype: int64

In [ ]:
series - 100

0   -99
1   -98
2   -97
3   -96
4   -95
dtype: int64

In [ ]:
print(series + 100)   # int
print(series - 100)   # int
print(series * 100)   # int
print(series ** 100)  # int
print(series / 100)   # float(float 몫)
print(series % 100)   # int
print(series // 100)  # int(int 몫)

0    101
1    102
2    103
3    104
4    105
dtype: int64
0   -99
1   -98
2   -97
3   -96
4   -95
dtype: int64
0    100
1    200
2    300
3    400
4    500
dtype: int64
0                      1
1                      0
2   -2984622845537545263
3                      0
4   -3842938066129721103
dtype: int64
0    0.01
1    0.02
2    0.03
3    0.04
4    0.05
dtype: float64
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    0
1    0
2    0
3    0
4    0
dtype: int64


## Series 객체에 접근
- keys -> index
- values

In [ ]:
series.keys

<bound method Series.keys of 0    1
1    2
2    3
3    4
4    5
dtype: int64>

In [ ]:
series.values

array([1, 2, 3, 4, 5])

In [ ]:
series.keys()

RangeIndex(start=0, stop=5, step=1)

In [ ]:
series.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s2 = pd.Series({'a':1, 'b':2, 'c':3, 'd':4})
print(s2.keys)

<bound method Series.keys of a    1
b    2
c    3
d    4
dtype: int64>


In [ ]:
s2.values

array([1, 2, 3, 4])

In [ ]:
print(s2.values[0])
print(series[0])

1
1


In [ ]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
# items

s2.items()  # zip -> 순회가 가능, 쌍으로 이루어져 있다

In [ ]:
for index, value in s2.items():
    print(f'인덱스 : {index}  데이터 : {value}')

인덱스 : a  데이터 : 1
인덱스 : b  데이터 : 2
인덱스 : c  데이터 : 3
인덱스 : d  데이터 : 4


In [ ]:
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

In [ ]:
s

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
s.loc['b']  # loc : 행에 접근

20

In [ ]:
s.loc['b':'d']

b    20
c    30
d    40
dtype: int64

In [ ]:
s.iloc[1]  # iloc : (행에 기반한) 열에 접근

20

In [ ]:
s.iloc[1:3]

b    20
c    30
dtype: int64

In [ ]:
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
print(series.loc[1:3])
print(series.iloc[1:3])

1    2
2    3
3    4
dtype: int64
1    2
2    3
dtype: int64


In [ ]:
s.at['a']  #  at : 하나의 값만 가져올 때

10

In [ ]:
s.iat[1]

20

In [ ]:
print(s.get('e')) # 없을 때 값 처리 방법이 다름, error가 나지 않고 없다는 걸 알려줌

None


In [ ]:
print(s.get('e', default=-1))  # error 대신에 -1

-1


## 결측값 (Nan, None)
Nan(Not a Number) -> float

None -> none
- isna()
- isnull()

In [ ]:
import numpy as np

In [ ]:
data = [1, 2, 3, None]

In [ ]:
print(np.array(data))

[1 2 3 None]


In [ ]:
print(pd.Series(data))

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64


In [ ]:
s = pd.Series(data)

In [ ]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [ ]:
s.isnull()

0    False
1    False
2    False
3     True
dtype: bool

In [ ]:
s.isnull().sum()  # True 개수

1

In [ ]:
s.notnull()

0     True
1     True
2     True
3    False
dtype: bool

In [ ]:
s.notnull().sum()

3

In [ ]:
# 결측치 제거

s.dropna()

0    1.0
1    2.0
2    3.0
dtype: float64

In [ ]:
# 결측치를 0으로 치환

s.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
dtype: float64

## Series 함수

In [ ]:
s = pd.Series([1, 3, 5, 7, 9])

In [ ]:
s.count()  # 카운트 함수

5

In [ ]:
s.min()  # 최소값

1

In [ ]:
s.max()  # 최대값

9

In [ ]:
print(s.mean())
print(s.median())
print(s.std())
print(s.var())

5.0
5.0
3.1622776601683795
10.0


In [ ]:
s.describe()  # 기초 통계 내용

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64